site_name: Knowledge-Base
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.tabs.sticky
  - navigation.top
  - search.suggest
  - search.highlight
  - search.share
  - navigation.footer
  - content.code.copy


  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search:
      lang: en
  # - social   # not working on windows due to gtk tools error and other errors which req cairo and dll's. 


repo_url: https://github.com/harshdeepsinghin/Knowledge-Base
repo_name: harshdeepsinghin/Knowledge-Base


extra_javascript:
  - javascripts/extra.js
  - javascripts/katex.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



nav:
  - Home: 
    - Introduction: "index.md"            


extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@harshdeepsingh.in


copyright: Copyright &copy; 2024 - 2025 Harshdeep Singh



