site_name: Knowledge-Base
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.tabs.sticky
  - navigation.top
  - search.suggest
  - search.highlight
  - search.share
  - navigation.footer
  - content.code.copy



  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search:
      lang: en
  - social 


repo_url: https://github.com/rohanbatrain/Knowledge-Base
repo_name: rohanbatrain/Knowledge-Base


extra_javascript:
  - javascripts/extra.js

  - javascripts/katex.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



nav:
  - Home: 
    - Introduction: "index.md"
    - Developement-Setup: "Home/Developement-Setup.md"
  - Developement-Setup: 
    - 'Android':
      - 'OnePlus': 
        - 'Kebab': 
            - 'Production': 
              - July-2023: 'Developement-Setup/Android/One-Plus/Kebab/2023/June/production.md'
            - 'Testing': 
              - Fresh-Device : "Developement-Setup/Android/One-Plus/Kebab/Testing/fresh-device.md"
              - Evolution-X : "Developement-Setup/Android/One-Plus/Kebab/Testing/evolution-x.md"
              - Kali-Nethunter : "Developement-Setup/Android/One-Plus/Kebab/Testing/kali-nethunter.md"
              - Lineage-OS : "Developement-Setup/Android/One-Plus/Kebab/Testing/lineage-os.md"


extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@rohanbatra.in


copyright: Copyright &copy; 2022 - 2023 Rohan Batra



