site_name: Knowledge-Base
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.suggest
  - search.highlight
  - search.share

plugins:
  - search:
      lang: en
  - social 



extra_javascript:
  - javascripts/extra.js

nav:
    - Home: 'index.md'
    - Developement-Setup: 
      - Android: 
        - OnePlus: 
          - Kebab: "developement-setup/Android/One-Plus/Kebab.md"
      - Windows: developement-setup/Windows.md
      - Linux: developement-setup/Linux.md      